<table class="col-sm-12 table table-hover table-striped  table-condensed tablesorter" id="sai_mod_page_table" style="word-break: break-all;">
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>group</th>
            <th>state</th>
            <th>div</th>
            <th>url</th>
            <!--th>parent_id</th>
            <th>login</th>
            <th>type</th>
            <th>func</th>
            <th>php_class</th-->
        </tr>
    </thead> 
    <tbody>
        ${content}
    </tbody>    
</table>