<?php 
\SYSTEM\autoload::registerFolder(dirname(__FILE__),'LIB');
require_once dirname(__FILE__).'/system/autoload.inc';
require_once dirname(__FILE__).'/markdown/autoload.inc';
require_once dirname(__FILE__).'/jquery/autoload.inc';
require_once dirname(__FILE__).'/tablesorter/autoload.inc';
require_once dirname(__FILE__).'/bootstrap/autoload.inc';
require_once dirname(__FILE__).'/tinymce/autoload.inc';
require_once dirname(__FILE__).'/textillate/autoload.inc';
require_once dirname(__FILE__).'/animate/autoload.inc';
require_once dirname(__FILE__).'/lettering/autoload.inc';