<table class="table table-hover table-condensed sai_table sai_margin_top_10" style="width: 100%">
    <tr>
        <th>${table_name}</th>
        <th>${table_open}</th>
        <th>${table_closed}</th>
        <th>${table_all}</th>
        <th>${table_done}</th>
    </tr>
    ${entries}
    <tr>
        <td>${table_project}</td>
        <td>${project_open}</td>
        <td>${project_closed}</td>
        <td>${project_all}</td>
        <td>${project}%</td>
    </tr>
    <tr>
        <th>${table_username}</th>
        <th>${table_open}</th>
        <th>${table_closed}</th>
        <th>${table_all}</th>
        <th>${table_done}</th>
    </tr>
    ${userstats}
</table>